-- Migration: add brief/identity/billing/credentials
-- Execute as one-off in Supabase SQL Editor

-- Proyectos: brief creativo
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='proyectos' AND column_name='brief') THEN
    ALTER TABLE public.proyectos ADD COLUMN brief JSONB DEFAULT '{}'::jsonb;
  END IF;
END $$;

-- Proyectos: cronograma compacto
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='proyectos' AND column_name='cronograma') THEN
    ALTER TABLE public.proyectos ADD COLUMN cronograma JSONB DEFAULT '[]'::jsonb;
  END IF;
END $$;

-- Clientes: identidad digital
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='clientes' AND column_name='identidad_digital') THEN
    ALTER TABLE public.clientes ADD COLUMN identidad_digital JSONB DEFAULT '{}'::jsonb;
  END IF;
END $$;

-- Tabla: credenciales y canales por proyecto
CREATE TABLE IF NOT EXISTS public.credenciales_proyecto (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  proyecto_id BIGINT NOT NULL REFERENCES public.proyectos(id) ON DELETE CASCADE,
  tipo TEXT NOT NULL DEFAULT 'canal',
  canal TEXT NOT NULL,
  usuario TEXT,
  contrasena TEXT,
  url TEXT,
  notas TEXT,
  created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT now() NOT NULL
);

ALTER TABLE public.credenciales_proyecto ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='credenciales_proyecto' AND policyname='credenciales_read_policy') THEN
    CREATE POLICY credenciales_read_policy ON public.credenciales_proyecto FOR SELECT USING (true);
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='credenciales_proyecto' AND policyname='credenciales_insert_policy') THEN
    CREATE POLICY credenciales_insert_policy ON public.credenciales_proyecto FOR INSERT WITH CHECK (true);
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='credenciales_proyecto' AND policyname='credenciales_update_policy') THEN
    CREATE POLICY credenciales_update_policy ON public.credenciales_proyecto FOR UPDATE USING (true);
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='credenciales_proyecto' AND policyname='credenciales_delete_policy') THEN
    CREATE POLICY credenciales_delete_policy ON public.credenciales_proyecto FOR DELETE USING (true);
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_credenciales_proyecto_id ON public.credenciales_proyecto(proyecto_id);
