import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
	route("/", "routes/home.tsx"),
	route("/login", "routes/login.tsx"),
	route("/dashboard", "routes/dashboard.tsx"),
	route("/clientes", "routes/clientes.tsx"),
	route("/clientes/:id", "routes/clientes-vista.tsx"),
	route("/servicios", "routes/servicios.tsx"),
	route("/ventas", "routes/ventas.tsx"),
	route("/tareas", "routes/tareas.tsx"),
	route("/proyectos", "routes/proyectos.tsx"),
	route("/email-marketing", "routes/email-marketing.tsx"),
	route("/chatbot", "routes/chatbot.tsx"),
	route("/calendario", "routes/calendario.tsx"),
	route("/reportes", "routes/reportes.tsx"),
	route("/estimador", "routes/estimador.tsx"),
	route("/kanban", "routes/kanban.tsx"),
	route("/configuracion", "routes/configuracion.tsx"),
	route("/equipo", "routes/equipo.tsx"),
	route("/facturacion", "routes/facturacion.tsx"),
	route("/contratos", "routes/contratos.tsx"),
	route("/agentes", "routes/agentes.tsx"),
	route("/whatsapp", "routes/whatsapp.tsx"),
	route("/public/proyecto/:id", "routes/public-proyecto.tsx"),
	route("/proyecto/:id", "routes/proyecto.tsx"),
] satisfies RouteConfig;
