-- ============================================================
-- CRM AGENCIA — SCHEMA COMPLETO EN SUPABASE (PRODUCCIÓN)
-- ============================================================

-- 1. EXTENSIONES
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- 2. TABLAS CORE
CREATE TABLE IF NOT EXISTS public.clientes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre text NOT NULL,
  email text UNIQUE NOT NULL,
  telefono text,
  empresa text,
  nicho text,
  origen text DEFAULT 'Referido',
  dolores text,
  necesidades text,
  intereses text,
  estado text DEFAULT 'Activo',
  ultima_interaccion text,
  created_at text DEFAULT now()::text,
  updated_at text DEFAULT now()::text
);

CREATE TABLE IF NOT EXISTS public.proyectos (
  id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  nombre text NOT NULL,
  descripcion text DEFAULT '',
  cliente_id bigint REFERENCES clientes(id) ON DELETE CASCADE,
  cliente_nombre text DEFAULT '',
  servicios text[] DEFAULT '{}',
  oportunidad_id bigint,
  estado text DEFAULT 'Activo',
  prioridad text DEFAULT 'Media',
  fecha_inicio text DEFAULT now()::text,
  fecha_fin text DEFAULT now()::text,
  progreso integer DEFAULT 0,
  presupuesto numeric DEFAULT 0,
  costo_actual numeric DEFAULT 0,
  tareas jsonb DEFAULT '[]'::jsonb,
  recursos jsonb DEFAULT '[]'::jsonb,
  monto_pagado numeric DEFAULT 0,
  onboarding_checklist jsonb DEFAULT '{}'::jsonb,
  estado_pago text DEFAULT 'pendiente',
  metodo_pago text,
  fase_administrativa text DEFAULT 'propuesta',
  plan_contenido jsonb DEFAULT '{}'::jsonb,
  creado_en text DEFAULT now()::text,
  actualizado_en text DEFAULT now()::text,
  estrategia jsonb DEFAULT '{}'::jsonb,
  canales jsonb DEFAULT '{}'::jsonb,
  contrato_url text,
  facturacion_detalle jsonb DEFAULT '{}'::jsonb,
  codigo text,
  brief jsonb DEFAULT '{}'::jsonb,
  cronograma jsonb DEFAULT '{}'::jsonb
);

CREATE TABLE IF NOT EXISTS public.tareas (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  titulo text NOT NULL,
  descripcion text DEFAULT '',
  fecha text DEFAULT now()::text,
  prioridad text DEFAULT 'Media',
  estado text DEFAULT 'Pendiente',
  tipo text DEFAULT 'Tarea',
  link_reunion text,
  created_at text DEFAULT now()::text,
  proyecto_id uuid REFERENCES proyectos(id) ON DELETE CASCADE,
  oportunidad_id bigint,
  cliente_id bigint,
  responsable_id bigint REFERENCES equipo(id),
  subtareas jsonb DEFAULT '[]'::jsonb,
  dependencias integer[] DEFAULT '{}',
  adjuntos jsonb DEFAULT '[]'::jsonb,
  comentarios jsonb DEFAULT '[]'::jsonb,
  recordatorios jsonb DEFAULT '[]'::jsonb,
  tiempo_inicio text,
  tiempo_pausa text,
  tiempo_fin text,
  tiempo_total integer DEFAULT 0,
  timer_activo boolean DEFAULT false
);

CREATE TABLE IF NOT EXISTS public.oportunidades (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre text NOT NULL,
  cliente_id bigint REFERENCES clientes(id) ON DELETE CASCADE,
  cliente_nombre text DEFAULT '',
  valor numeric DEFAULT 0,
  servicios_interes text[] DEFAULT '{}',
  fecha_cierre_esperada text,
  etapa text DEFAULT 'contacto',
  probabilidad integer DEFAULT 50,
  estado text DEFAULT 'Abierta',
  created_at text DEFAULT now()::text
);

CREATE TABLE IF NOT EXISTS public.transacciones (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  concepto text NOT NULL,
  monto numeric NOT NULL DEFAULT 0,
  tipo text DEFAULT 'ingreso',
  estado text DEFAULT 'pendiente',
  fecha text DEFAULT now()::text,
  cliente_id bigint REFERENCES clientes(id),
  proyecto_id uuid REFERENCES proyectos(id),
  factura_id bigint,
  created_at text DEFAULT now()::text
);

CREATE TABLE IF NOT EXISTS public.facturas (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  numero text UNIQUE NOT NULL,
  concepto text DEFAULT '',
  monto numeric DEFAULT 0,
  estado text DEFAULT 'pendiente',
  fecha_emision text DEFAULT now()::text,
  fecha_vencimiento text,
  cliente_id bigint REFERENCES clientes(id),
  proyecto_id uuid REFERENCES proyectos(id),
  items jsonb DEFAULT '[]'::jsonb,
  metodo_pago text,
  created_at text DEFAULT now()::text
);

CREATE TABLE IF NOT EXISTS public.contratos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  titulo text NOT NULL,
  cliente_id bigint REFERENCES clientes(id) ON DELETE CASCADE,
  proyecto_id uuid REFERENCES proyectos(id) ON DELETE CASCADE,
  contenido text DEFAULT '',
  estado text DEFAULT 'borrador',
  fecha_inicio text,
  fecha_fin text,
  monto numeric DEFAULT 0,
  clausulas jsonb DEFAULT '[]'::jsonb,
  created_at text DEFAULT now()::text
);

CREATE TABLE IF NOT EXISTS public.servicios (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre text NOT NULL,
  categoria text DEFAULT 'general',
  descripcion text DEFAULT '',
  precio_base numeric DEFAULT 0,
  duracion text DEFAULT '1 mes',
  incluye text[] DEFAULT '{}',
  estado text DEFAULT 'Activo',
  popularidad integer DEFAULT 0,
  tipo text DEFAULT 'individual',
  paquete_dias integer,
  objetivo text[] DEFAULT '{}',
  incluye_paquete text[] DEFAULT '{}',
  precio_paquete numeric DEFAULT 0,
  created_at text DEFAULT now()::text
);

CREATE TABLE IF NOT EXISTS public.equipo (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre text NOT NULL,
  email text UNIQUE NOT NULL,
  rol text DEFAULT 'Soporte',
  especialidad text DEFAULT '',
  estado text DEFAULT 'Activo',
  created_at text DEFAULT now()::text
);

CREATE TABLE IF NOT EXISTS public.n8n_events (
  id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  direccion text DEFAULT 'entrada',
  fuente text DEFAULT 'crm',
  tipo_evento text DEFAULT 'webhook',
  payload jsonb DEFAULT '{}'::jsonb,
  estado text DEFAULT 'pendiente',
  fecha_procesamiento text DEFAULT now()::text
);

CREATE TABLE IF NOT EXISTS public.configuracion_empresa (
  id bigint PRIMARY KEY DEFAULT 1,
  nombre_agencia text DEFAULT 'DESEO DIGITAL',
  email_contacto text DEFAULT 'emprende.villavo@gmail.com',
  telefono text,
  website text,
  logo_url text,
  colores jsonb DEFAULT '{}'::jsonb,
  descripcion text DEFAULT '',
  direccion text,
  ciudad text DEFAULT 'Villavicencio',
  pais text DEFAULT 'Colombia',
  actualizado_en text DEFAULT now()::text,
  google_business_link text
);

CREATE TABLE IF NOT EXISTS public.documentos (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  titulo text NOT NULL,
  tipo text DEFAULT 'pdf',
  url text NOT NULL,
  proyecto_id uuid REFERENCES proyectos(id),
  cliente_id bigint REFERENCES clientes(id),
  creado_en text DEFAULT now()::text
);

-- 3. ÍNDICES
CREATE INDEX IF NOT EXISTS idx_proyectos_cliente ON public.proyectos(cliente_id);
CREATE INDEX IF NOT EXISTS idx_tareas_proyecto ON public.tareas(proyecto_id);
CREATE INDEX IF NOT EXISTS idx_tareas_cliente ON public.tareas(cliente_id);
CREATE INDEX IF NOT EXISTS idx_transacciones_cliente ON public.transacciones(cliente_id);
CREATE INDEX IF NOT EXISTS idx_transacciones_proyecto ON public.transacciones(proyecto_id);
CREATE INDEX IF NOT EXISTS idx_facturas_proyecto ON public.facturas(proyecto_id);
CREATE INDEX IF NOT EXISTS idx_contratos_cliente ON public.contratos(cliente_id);
CREATE INDEX IF NOT EXISTS idx_contratos_proyecto ON public.contratos(proyecto_id);

-- 4. RLS PARA TODAS LAS TABLAS
ALTER TABLE public.clientes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.proyectos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tareas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.oportunidades ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.transacciones ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.facturas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.contratos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.servicios ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.equipo ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.n8n_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.configuracion_empresa ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.documentos ENABLE ROW LEVEL SECURITY;

-- Políticas públicas (MVP - permitir todo a authenticated yanon)
DO $$
BEGIN
  -- clientes
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='clientes' AND policyname='Allow read') THEN
    CREATE POLICY "Allow read" ON public.clientes FOR SELECT USING (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='clientes' AND policyname='Allow insert') THEN
    CREATE POLICY "Allow insert" ON public.clientes FOR INSERT WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='clientes' AND policyname='Allow update') THEN
    CREATE POLICY "Allow update" ON public.clientes FOR UPDATE USING (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='clientes' AND policyname='Allow delete') THEN
    CREATE POLICY "Allow delete" ON public.clientes FOR DELETE USING (true);
  END IF;

  -- proyectos
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='proyectos' AND policyname='Allow read') THEN
    CREATE POLICY "Allow read" ON public.proyectos FOR SELECT USING (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='proyectos' AND policyname='Allow insert') THEN
    CREATE POLICY "Allow insert" ON public.proyectos FOR INSERT WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='proyectos' AND policyname='Allow update') THEN
    CREATE POLICY "Allow update" ON public.proyectos FOR UPDATE USING (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='proyectos' AND policyname='Allow delete') THEN
    CREATE POLICY "Allow delete" ON public.proyectos FOR DELETE USING (true);
  END IF;

  -- tareas
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='tareas' AND policyname='Allow read') THEN
    CREATE POLICY "Allow read" ON public.tareas FOR SELECT USING (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='tareas' AND policyname='Allow insert') THEN
    CREATE POLICY "Allow insert" ON public.tareas FOR INSERT WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='tareas' AND policyname='Allow update') THEN
    CREATE POLICY "Allow update" ON public.tareas FOR UPDATE USING (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='tareas' AND policyname='Allow delete') THEN
    CREATE POLICY "Allow delete" ON public.tareas FOR DELETE USING (true);
  END IF;

  -- oportunidades
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='oportunidades' AND policyname='Allow read') THEN
    CREATE POLICY "Allow read" ON public.oportunidades FOR SELECT USING (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='oportunidades' AND policyname='Allow insert') THEN
    CREATE POLICY "Allow insert" ON public.oportunidades FOR INSERT WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='oportunidades' AND policyname='Allow update') THEN
    CREATE POLICY "Allow update" ON public.oportunidades FOR UPDATE USING (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='oportunidades' AND policyname='Allow delete') THEN
    CREATE POLICY "Allow delete" ON public.oportunidades FOR DELETE USING (true);
  END IF;

  -- transacciones
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='transacciones' AND policyname='Allow read') THEN
    CREATE POLICY "Allow read" ON public.transacciones FOR SELECT USING (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='transacciones' AND policyname='Allow insert') THEN
    CREATE POLICY "Allow insert" ON public.transacciones FOR INSERT WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='transacciones' AND policyname='Allow update') THEN
    CREATE POLICY "Allow update" ON public.transacciones FOR UPDATE USING (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='transacciones' AND policyname='Allow delete') THEN
    CREATE POLICY "Allow delete" ON public.transacciones FOR DELETE USING (true);
  END IF;

  -- facturas
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='facturas' AND policyname='Allow read') THEN
    CREATE POLICY "Allow read" ON public.facturas FOR SELECT USING (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='facturas' AND policyname='Allow insert') THEN
    CREATE POLICY "Allow insert" ON public.facturas FOR INSERT WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='facturas' AND policyname='Allow update') THEN
    CREATE POLICY "Allow update" ON public.facturas FOR UPDATE USING (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='facturas' AND policyname='Allow delete') THEN
    CREATE POLICY "Allow delete" ON public.facturas FOR DELETE USING (true);
  END IF;

  -- contratos
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='contratos' AND policyname='Allow read') THEN
    CREATE POLICY "Allow read" ON public.contratos FOR SELECT USING (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='contratos' AND policyname='Allow insert') THEN
    CREATE POLICY "Allow insert" ON public.contratos FOR INSERT WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='contratos' AND policyname='Allow update') THEN
    CREATE POLICY "Allow update" ON public.contratos FOR UPDATE USING (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='contratos' AND policyname='Allow delete') THEN
    CREATE POLICY "Allow delete" ON public.contratos FOR DELETE USING (true);
  END IF;

  -- servicios
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='servicios' AND policyname='Allow read') THEN
    CREATE POLICY "Allow read" ON public.servicios FOR SELECT USING (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='servicios' AND policyname='Allow insert') THEN
    CREATE POLICY "Allow insert" ON public.servicios FOR INSERT WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='servicios' AND policyname='Allow update') THEN
    CREATE POLICY "Allow update" ON public.servicios FOR UPDATE USING (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='servicios' AND policyname='Allow delete') THEN
    CREATE POLICY "Allow delete" ON public.servicios FOR DELETE USING (true);
  END IF;

  -- equipo
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='equipo' AND policyname='Allow read') THEN
    CREATE POLICY "Allow read" ON public.equipo FOR SELECT USING (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='equipo' AND policyname='Allow insert') THEN
    CREATE POLICY "Allow insert" ON public.equipo FOR INSERT WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='equipo' AND policyname='Allow update') THEN
    CREATE POLICY "Allow update" ON public.equipo FOR UPDATE USING (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='equipo' AND policyname='Allow delete') THEN
    CREATE POLICY "Allow delete" ON public.equipo FOR DELETE USING (true);
  END IF;

  -- n8n_events
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='n8n_events' AND policyname='Allow read') THEN
    CREATE POLICY "Allow read" ON public.n8n_events FOR SELECT USING (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='n8n_events' AND policyname='Allow insert') THEN
    CREATE POLICY "Allow insert" ON public.n8n_events FOR INSERT WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='n8n_events' AND policyname='Allow update') THEN
    CREATE POLICY "Allow update" ON public.n8n_events FOR UPDATE USING (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='n8n_events' AND policyname='Allow delete') THEN
    CREATE POLICY "Allow delete" ON public.n8n_events FOR DELETE USING (true);
  END IF;

  -- configuracion_empresa
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='configuracion_empresa' AND policyname='Allow read') THEN
    CREATE POLICY "Allow read" ON public.configuracion_empresa FOR SELECT USING (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='configuracion_empresa' AND policyname='Allow insert') THEN
    CREATE POLICY "Allow insert" ON public.configuracion_empresa FOR INSERT WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='configuracion_empresa' AND policyname='Allow update') THEN
    CREATE POLICY "Allow update" ON public.configuracion_empresa FOR UPDATE USING (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='configuracion_empresa' AND policyname='Allow delete') THEN
    CREATE POLICY "Allow delete" ON public.configuracion_empresa FOR DELETE USING (true);
  END IF;

  -- documentos
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='documentos' AND policyname='Allow read') THEN
    CREATE POLICY "Allow read" ON public.documentos FOR SELECT USING (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='documentos' AND policyname='Allow insert') THEN
    CREATE POLICY "Allow insert" ON public.documentos FOR INSERT WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='documentos' AND policyname='Allow update') THEN
    CREATE POLICY "Allow update" ON public.documentos FOR UPDATE USING (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='documentos' AND policyname='Allow delete') THEN
    CREATE POLICY "Allow delete" ON public.documentos FOR DELETE USING (true);
  END IF;
END $$;

-- 5. SEED INICIAL EN SUPABASE
INSERT INTO public.configuracion_empresa (id, nombre_agencia, email_contacto) VALUES (1, 'DESEO DIGITAL', 'emprende.villavo@gmail.com') ON CONFLICT (id) DO NOTHING;
